### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by vovanb** [ActiDoo/gamification-engine#103]
Hello,
I am trying to install docker development on windows docker desktop and got below error:
>docker-compose up
[+] Running 0/1
 - python Error                                                                                                    2.6s
[+] Building 16.9s (15/18)
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.6-alpine3.10                                           1.2s
 => [ 1/14] FROM docker.io/library/python:3.6-alpine3.10@sha256:8265d64bda031950d0423578a7193df0ca4d91d53d4f2b685  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 11.69kB                                                                               0.0s
 => CACHED [ 2/14] WORKDIR /usr/src/app                                                                            0.0s
 => CACHED [ 3/14] RUN apk add --no-cache postgresql-dev build-base musl-dev libffi libffi-dev bash                0.0s
 => CACHED [ 4/14] RUN addgroup -S gengine                                                                         0.0s
 => CACHED [ 5/14] RUN adduser -S -D -h /usr/src/app gengine gengine                                               0.0s
 => CACHED [ 6/14] RUN mkdir /run/uwsgi                                                                            0.0s
 => CACHED [ 7/14] RUN chown -R gengine:gengine /run/uwsgi                                                         0.0s
 => CACHED [ 8/14] COPY requirements.txt ./                                                                        0.0s
 => CACHED [ 9/14] COPY optional-requirements.txt ./                                                               0.0s
 => CACHED [10/14] COPY docker-files/* ./                                                                          0.0s
 => ERROR [11/14] RUN cat optional-requirements.txt >> requirements.txt && pip install -r requirements.txt        15.5s
------
 > [11/14] RUN cat optional-requirements.txt >> requirements.txt && pip install -r requirements.txt:
#15 1.715 Collecting alembic==0.9.1
#15 1.777   Downloading alembic-0.9.1.tar.gz (999 kB)
#15 2.546 Collecting appdirs==1.4.3
#15 2.553   Downloading appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
#15 2.604 Collecting certifi==2019.6.16
#15 2.619   Downloading certifi-2019.6.16-py2.py3-none-any.whl (157 kB)
#15 2.693 Collecting Chameleon==3.1
#15 2.704   Downloading Chameleon-3.1.tar.gz (159 kB)
#15 3.133 Collecting chardet==3.0.4
#15 3.142   Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
#15 3.237 Collecting Click==7.0
#15 3.247   Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
#15 3.293 Collecting contextlib2==0.5.5
#15 3.299   Downloading contextlib2-0.5.5-py2.py3-none-any.whl (8.1 kB)
#15 3.384 Collecting croniter==0.3.16
#15 3.392   Downloading croniter-0.3.16.tar.gz (16 kB)
#15 3.720 Collecting dogpile.cache==0.6.2
#15 3.733   Downloading dogpile.cache-0.6.2.tar.gz (329 kB)
#15 4.137 Collecting Flask==1.1.1
#15 4.147   Downloading Flask-1.1.1-py2.py3-none-any.whl (94 kB)
#15 4.215 Collecting Flask-Admin==1.5.3
#15 4.239   Downloading Flask-Admin-1.5.3.tar.gz (1.7 MB)
#15 4.916 Collecting hupper==0.4.4
#15 4.925   Downloading hupper-0.4.4-py2.py3-none-any.whl (18 kB)
#15 4.978 Collecting idna==2.8
#15 4.990   Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
#15 5.033 Collecting itsdangerous==1.1.0
#15 5.042   Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
#15 5.108 Collecting Jinja2==2.10.1
#15 5.117   Downloading Jinja2-2.10.1-py2.py3-none-any.whl (124 kB)
#15 5.167 Collecting jsl==0.2.4
#15 5.176   Downloading jsl-0.2.4.tar.gz (21 kB)
#15 5.511 Collecting jsonschema==2.6.0
#15 5.519   Downloading jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
#15 5.579 Collecting Mako==1.0.6
#15 5.599   Downloading Mako-1.0.6.tar.gz (575 kB)
#15 6.140 Collecting MarkupSafe==1.1.1
#15 6.163   Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
#15 6.506 Collecting mock==2.0.0
#15 6.516   Downloading mock-2.0.0-py2.py3-none-any.whl (56 kB)
#15 6.596 Collecting packaging==16.8
#15 6.605   Downloading packaging-16.8-py2.py3-none-any.whl (23 kB)
#15 6.647 Collecting PasteDeploy==1.5.2
#15 6.654   Downloading PasteDeploy-1.5.2-py2.py3-none-any.whl (18 kB)
#15 6.719 Collecting plaster==1.0
#15 6.732   Downloading plaster-1.0-py2.py3-none-any.whl (14 kB)
#15 6.778 Collecting plaster-pastedeploy==0.6
#15 6.785   Downloading plaster_pastedeploy-0.6-py2.py3-none-any.whl (7.8 kB)
#15 6.969 Collecting psycopg2==2.8.3
#15 6.984   Downloading psycopg2-2.8.3.tar.gz (377 kB)
#15 7.430 Collecting Pygments==2.2.0
#15 7.450   Downloading Pygments-2.2.0-py2.py3-none-any.whl (841 kB)
#15 7.633 Collecting pymemcache==1.4.2
#15 7.641   Downloading pymemcache-1.4.2-py2.py3-none-any.whl (38 kB)
#15 7.756 Collecting pyparsing==2.2.0
#15 7.766   Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
#15 7.868 Collecting pyramid==1.9.1
#15 7.888   Downloading pyramid-1.9.1-py2.py3-none-any.whl (582 kB)
#15 8.045 Collecting pyramid-chameleon==0.3
#15 8.053   Downloading pyramid_chameleon-0.3.tar.gz (28 kB)
#15 8.400 Collecting pyramid-debugtoolbar==3.0.5
#15 8.416   Downloading pyramid_debugtoolbar-3.0.5-py2.py3-none-any.whl (353 kB)
#15 8.520 Collecting pyramid-dogpile-cache==0.0.4
#15 8.527   Downloading pyramid_dogpile_cache-0.0.4.tar.gz (5.2 kB)
#15 8.841 Collecting pyramid-jinja2==2.6.2
#15 8.852   Downloading pyramid_jinja2-2.6.2-py2.py3-none-any.whl (68 kB)
#15 8.910 Collecting pyramid-mako==1.0.2
#15 8.927   Downloading pyramid_mako-1.0.2.tar.gz (37 kB)
#15 9.264 Collecting pyramid-swagger-spec==0.0.7
#15 9.276   Downloading pyramid_swagger_spec-0.0.7.tar.gz (8.2 kB)
#15 9.672 Collecting pyramid-tm==1.1.1
#15 9.684   Downloading pyramid_tm-1.1.1-py2.py3-none-any.whl (15 kB)
#15 9.737 Collecting python-crontab==2.2.2
#15 9.750   Downloading python-crontab-2.2.2.tar.gz (44 kB)
#15 10.09 Collecting python-dateutil==2.5.3
#15 10.11   Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201 kB)
#15 10.16 Collecting python-editor==1.0.3
#15 10.16   Downloading python-editor-1.0.3.tar.gz (7.0 kB)
#15 10.62 Collecting pytz==2016.10
#15 10.63   Downloading pytz-2016.10-py2.py3-none-any.whl (483 kB)
#15 10.87 Collecting raven==6.0.0
#15 10.89   Downloading raven-6.0.0-py2.py3-none-any.whl (279 kB)
#15 10.97 Collecting repoze.lru==0.6
#15 10.99   Downloading repoze.lru-0.6.tar.gz (19 kB)
#15 11.31 Collecting six==1.10.0
#15 11.32   Downloading six-1.10.0-py2.py3-none-any.whl (10 kB)
#15 11.87 Collecting SQLAlchemy==1.3.0
#15 11.88   Downloading SQLAlchemy-1.3.0.tar.gz (5.9 MB)
#15 13.33 Collecting transaction==2.1.2
#15 13.35   Downloading transaction-2.1.2-py2.py3-none-any.whl (51 kB)
#15 13.40 Collecting translationstring==1.3
#15 13.41   Downloading translationstring-1.3-py2.py3-none-any.whl (15 kB)
#15 13.50 Collecting urllib3==1.25.3
#15 13.52   Downloading urllib3-1.25.3-py2.py3-none-any.whl (150 kB)
#15 13.58 Collecting venusian==1.0
#15 13.59   Downloading venusian-1.0.tar.gz (45 kB)
#15 13.95 Collecting waitress==1.4.2
#15 13.97   Downloading waitress-1.4.2-py2.py3-none-any.whl (148 kB)
#15 14.06 Collecting WebOb==1.7.2
#15 14.07   Downloading WebOb-1.7.2-py2.py3-none-any.whl (83 kB)
#15 14.16 Collecting Werkzeug==0.16.0
#15 14.18   Downloading Werkzeug-0.16.0-py2.py3-none-any.whl (327 kB)
#15 14.27 Collecting WTForms==2.2.1
#15 14.29   Downloading WTForms-2.2.1-py2.py3-none-any.whl (166 kB)
#15 14.36 Collecting zope.deprecation==4.2.0
#15 14.37   Downloading zope.deprecation-4.2.0-py2.py3-none-any.whl (10 kB)
#15 14.72 Collecting zope.interface==4.4.2
#15 14.74   Downloading zope.interface-4.4.2.tar.gz (150 kB)
#15 14.97     ERROR: Command errored out with exit status 1:
#15 14.97      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1wpivbb2/zope.interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1wpivbb2/zope.interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gbgg_c6w
#15 14.97          cwd: /tmp/pip-install-1wpivbb2/zope.interface/
#15 14.97     Complete output (5 lines):
#15 14.97     Traceback (most recent call last):
#15 14.97       File "<string>", line 1, in <module>
#15 14.97       File "/tmp/pip-install-1wpivbb2/zope.interface/setup.py", line 26, in <module>
#15 14.97         from setuptools import setup, Extension, Feature
#15 14.97     ImportError: cannot import name 'Feature'
#15 14.97     ----------------------------------------
#15 14.97 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#15 15.17 WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
#15 15.17 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: executor failed running [/bin/sh -c cat optional-requirements.txt >> requirements.txt && pip install -r requirements.txt]: exit code: 1

**Comment by j2l** [comment]
I have the same issue. Did you find a solution?

**Comment by j2l** [comment]
Edit: There's a solution [here](https://github.com/ActiDoo/gamification-engine/issues/69)
