### ISSUE TITLE
ImportError: cannot import name 'Feature' (tried on Docker)

### ISSUE THREAD

**Issue by romdim** [ActiDoo/gamification-engine#69]
Got error:

```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_qpv24pz/zope.interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_qpv24pz/zope.interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sa3c96k8
         cwd: /tmp/pip-install-_qpv24pz/zope.interface/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_qpv24pz/zope.interface/setup.py", line 26, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
```

When running the docker-compose.
Resolved it when I updated `zope.interface` to latest: `zope.interface==5.2.0`.

**Comment by RRunner1337** [comment]
Got the same error when running docker-compose. Seems that if I added 

`
RUN pip install --upgrade pip setuptools==45.2.0
`
in between lines

> COPY docker-files/* ./
> RUN cat optional-requirements.txt >> requirements.txt && pip install -r requirements.txt

of Dockerfile it also compiled. Deferentially needs some love and maintenance :)

**Comment by msander** [comment]
> Deferentially needs some love and maintenance :)
@RRunner1337 I'd be happy to welcome you as a contributor :-) Can you create a pull request?

**Comment by j2l** [comment]
Thank you @romdim 
I had the same issue and `RUN pip install --upgrade pip setuptools==45.2.0` + `zope.interface==5.2.0` made it work. Maybe only one of these is enough?
Please note that it didn't work for [others](https://github.com/ActiDoo/gamification-engine/issues/103)
